language: asm
sudo: required
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends vice
script:
  - ./gradlew
notifications:
  email:
    on_success: change
    on_failure: change
