language: asm
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/c64lib/travis-ci/master/install.sh)
script:
  - cpm 64spec https://github.com/c64lib/64spec/archive/0.7.0pr.tar.gz
  - ./gradlew build
notifications:
  email:
    on_success: change
    on_failure: change
